name: Build and Deploy

on:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          tags: ghcr.io/beeper/maubot-runner:${{ github.sha }}
          push: true
          build-args: |
            COMMIT_HASH=${{ github.sha }}

  deploy-docker:
    runs-on: ubuntu-latest
    needs:
      - build-docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: beeper/docker-retag-push-latest@main
        with:
          image: ghcr.io/beeper/maubot-runner
